Sprint 3
madatsci/urlshortener pull request #3
Opened 2024-09-17 18:18 UTC by madatsci

2024-09-19 07:26 UTC, Bazys requested changes
много неиспльзуемых параметров и всегда проверятьошибки

2024-09-19 07:26 UTC, Bazys commented on internal/app/server/server.go
> +func New(ctx context.Context, config *config.Config, store store.Store, logger *zap.SugaredLogger) (*Server, error) {
Параметр функции, названный `ctx`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `ctx` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-09-19 07:26 UTC, Bazys commented on internal/app/store/database/store.go
> +	tx.ExecContext(ctx, `
1. не проверяешь ошибку
2. В продакшн средах так обычно не делают `IF NOT EXISTS` не сработает, если тебе надо будет поменять тип поля в таблице. Поэтому рекомендую изучить миграторы (го миграте или гусь)

2024-09-20 14:42 UTC, madatsci commented on internal/app/logger/logger.go
> +	defer logger.Sync() //nolint:errcheck
@Bazys Не уверен, как правильно нужно поступить здесь. Если проверять ошибку, в логах будет срач при остановке приложения.

2024-09-20 14:42 UTC, madatsci commented on internal/app/store/database/store.go
> +	defer tx.Rollback() //nolint:errcheck
@Bazys И вот здесь тоже будет ошибка, если был успешный коммит.

2024-09-23 07:57 UTC, merged